%% build_generalized_phy_model_5gtoolbox_5000.m
% Build the larger-sample 5G Toolbox-backed generalized PHY dataset and models.

clear;
clc;

rrp = rr_paths();
build_generalized_phy_model_5gtoolbox_core( ...
    rrp.resultsRoot, ...
    "phy_model_outputs_5gtoolbox_5000", ...
    5000, ...
    inf);
