%% build_generalized_phy_model_5gtoolbox.m
% Build the standard 5G Toolbox-backed generalized PHY dataset and models.

clear;
clc;

rrp = rr_paths();
build_generalized_phy_model_5gtoolbox_core( ...
    rrp.resultsRoot, ...
    "phy_model_outputs_5gtoolbox", ...
    2500, ...
    2);
